
/*
 * action types
 */

/// BASIC
export const IS_LOADING = 'IS_LOADING';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const CHANGE_MENU_STATE = 'CHANGE_MENU_STATE';

/// ORDERS_LIST
export const HANDLE_CHECK_ALL = 'HANDLE_CHECK_ALL';
export const HANDLE_CHECK_ITEM = 'HANDLE_CHECK_ITEM';
export const HIDE_FILTER_FIELDS = 'HIDE_FILTER_FIELDS';
export const HANDLE_FILTER_FIELD_STATE = 'HANDLE_FILTER_FIELD_STATE';

/// ORDER
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ORDER = 'DELETE_ORDER';
export const GET_ORDER_DATA = 'GET_ORDER_DATA';

/// HOME
export const GET_NEW_USERS_LIST = 'GET_NEW_USERS_LIST';
export const GET_PENDING_REVIEWS_LIST = 'GET_PENDING_REVIEWS_LIST';



//export const GET_RANDOM_NEW_USERS = 'GET_RANDOM_NEW_USERS';



